### ISSUE TITLE
Route mocking tests for Laravel 5.2 and 5.3

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-geo-routes#9]
Currently the tests that mock requests and test their output are skipped on Laravel 5.2 and 5.3, because their request testing APIs differ from 5.4 and up.

Tests need to be added that support version 5.2 and 5.3 as well, @yak0d3 mentioned the idea of using PHPUnit groups for this

**Comment by yak0d3** [comment]
I have implemented the PHPUnit groups in PR #13

**Comment by axlon** [comment]
While this is a more elegant solution to avoiding the tests in lower versions, it doesn't fully solve the problem: which is that in Laravel versions lower than 5.4 we don't test if the middleware manipulates requests correctly

**Comment by yak0d3** [comment]
I probably have found a potential solution, i am currently working on it, i'll submit a PR if everything goes great.

**Comment by axlon** [comment]
See PR #22
